# Generated by Django 3.0.6 on 2020-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Хелп текст', max_length=100, unique=True, verbose_name='Маршруты')),
                ('from_city', models.CharField(max_length=100, verbose_name='Откуда')),
                ('to_city', models.CharField(max_length=100, verbose_name='Куда')),
                ('travel_times', models.IntegerField(blank=True, max_length=50, verbose_name='Время в пути')),
                ('transit_cities', models.ManyToManyField(blank=True, to='trains.Train', verbose_name='Транзитные города')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['name'],
            },
        ),
    ]
