# Generated by Django 3.0.6 on 2020-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='travel_times',
            field=models.IntegerField(blank=True, verbose_name='Время в пути'),
        ),
    ]
